### ISSUE TITLE
Failed to connect to any resolved endpoint?

### ISSUE THREAD

**Issue by yutiansut** [laoshanxi/app-manager#37]
Usage:  appc [COMMAND] [ARG...] [flags]
root@quantaxis-PowerEdge-R610:/home/quantaxis# appc view
Failed to connect to any resolved endpoint
root@quantaxis-PowerEdge-R610:/home/quantaxis# appc reg -n ping -c 'ping www.baidu.com' -o 10
Failed to connect to any resolved endpoint
root@quantaxis-PowerEdge-R610:/home/quantaxis#

**Comment by yutiansut** [comment]
system : ubuntu16.06 64
program version : 1.5.3

install using:

```
dkpg -i appmanager_1.5.2_amd64.deb
```

apt install -y appmanager_1.5.2_amd64.deb report a bug error, so using dkpg

```
root@quantaxis-PowerEdge-R610:/home/quantaxis# dpkg -i appmanager_1.5.3_amd64.deb
Selecting previously unselected package appmanager.
(Reading database ... 358501 files and directories currently installed.)
Preparing to unpack appmanager_1.5.3_amd64.deb ...
Unpacking appmanager (1.5.3) ...
Setting up appmanager (1.5.3) ...
appmanager.service is not a native service, redirecting to systemd-sysv-install
Executing /lib/systemd/systemd-sysv-install enable appmanager
root@quantaxis-PowerEdge-R610:/home/quantaxis# appc
```

**Comment by yutiansut** [comment]
```
root@quantaxis-PowerEdge-R610:/home/quantaxis# /lib/systemd/systemd-sysv-install enable appmanager
root@quantaxis-PowerEdge-R610:/home/quantaxis# dpkg -l appmanager
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                                  Version                         Architecture                    Description
+++-=====================================================-===============================-===============================-================================================================================================================
ii  appmanager                                            1.5.3                           amd64                           github
root@quantaxis-PowerEdge-R610:/home/quantaxis#
```

**Comment by yutiansut** [comment]
another system: ubuntu

```
root@DESKTOP-FJF9FHQ:/mnt/c/Users/yutiansut/Downloads# dpkg -i appmanager_1.5.3_amd64.deb
Selecting previously unselected package appmanager.
(Reading database ... 28645 files and directories currently installed.)
Preparing to unpack appmanager_1.5.3_amd64.deb ...
Unpacking appmanager (1.5.3) ...
Setting up appmanager (1.5.3) ...
appmanager.service is not a native service, redirecting to systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable appmanager
System has not been booted with systemd as init system (PID 1). Can't operate.
dpkg: error processing package appmanager (--install):
 installed appmanager package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 appmanager
```

**Comment by yutiansut** [comment]
dpkg: error processing package appmanager (--install):
 installed appmanager package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 appmanager

**Comment by laoshanxi** [comment]
your installation seems failed, you can try the latest package and use yum install again

**Comment by laoshanxi** [comment]
first you need check your service whether started or not, do not try this on windows WSL, windows WSL do not have service management.

**Comment by laoshanxi** [comment]
> 
> 
> dpkg: error processing package appmanager (--install):
> installed appmanager package post-installation script subprocess returned error exit status 1
> Errors were encountered while processing:
> appmanager

Does your issue resolved?

**Comment by yutiansut** [comment]
nonono  it's not my fault ,  there is something wrong in your bash scripts, my friend help me modify and  it can cuurently run correctly ,  however i don't know which .sh file to modify. later i'll ask my friend and reply you~

**Comment by yutiansut** [comment]
@laoshanxi here it is:

https://github.com/laoshanxi/app-manager/blob/master/script/appmg-entrypoint.sh#L22

the script left ``` ;then``` in if caluse

**Comment by yutiansut** [comment]
```
if [ -z $APPMGR_OVERRIDE_LISTEN_PORT ]; then
	log "APPMGR_OVERRIDE_LISTEN_PORT from env:${APPMGR_OVERRIDE_LISTEN_PORT}"
fi
```

**Comment by yutiansut** [comment]
i give a pr  in https://github.com/laoshanxi/app-manager/pull/40

**Comment by laoshanxi** [comment]
so you are using Windows WSL ubuntu? for standard Ubuntu, and CentOS,  I used systemd instead of appmg-entrypoint.sh, this is mainly used for Docker container, anyway thanks for point out the issue.

**Comment by yutiansut** [comment]
emm i mainly use docker  or ubuntu 16.04, seems that both get this same error,  but use this modified sh, it can currently been started correctly

**Comment by yutiansut** [comment]
i worked in  quantitative financial industry, there are large amounts of long_running application in the same time, sometimes U have to schedule new applications (like new strategies/ simualtions) so this app-manager with a webpage ui is truly useful for this scenarios ~

**Comment by laoshanxi** [comment]
yeah, both docker and Windows WSL ubuntu would have this issue, because my recent test is under VM.

App-Manager is target to be a middle-ware that can be usefull for IT deployment.
